"""
Layer 11 -- Baryogenesis: η_B from Emergence.

Companion code for:
    Kahsay, Kibrom Kidane (2026). The Innocent Lepton.
    Zenodo. https://doi.org/10.5281/zenodo.19899091
    Kahsay, Kibrom Kidane (2026). One Substrate, Three Generations.
    Zenodo. https://doi.org/10.5281/zenodo.20069456
    Kahsay, Kibrom Kidane (2026). The Echo of Standing Waves.
    Zenodo. https://doi.org/10.5281/zenodo.20144381

Derives the baryon-to-photon ratio η_B from the E₈ algebraic data
with no tunable inputs.  No Yukawa dressing, no Boltzmann
equations, no washout approximations.  Pure emergence.

The formula:

    η_B  =  dim(G₂_fund) × J_lep × exp(−h∨(G₂) π²/2)
         =  7 × J_lep × exp(−2π²)

encodes the three Sakharov conditions as algebraic factors:

  ┌──────────────────────────────────────────────────────────────┐
  │  Factor           Sakharov condition     Algebraic source    │
  │  ──────           ──────────────────     ────────────────    │
  │  exp(−2π²)        B−L violation          G₂ instanton        │
  │  J_lep            C and CP violation     Fano orientation    │
  │  7                multiplicity           dim(7 of G₂)       │
  └──────────────────────────────────────────────────────────────┘

WHY these three factors and nothing else:

  (1) exp(−h∨(G₂) π²/2)  =  exp(−2π²)

      The Majorana mass that violates B−L is generated by a G₂
      instanton.  The instanton action is S = h∨(G₂) π²/2 = 2π²
      (dual Coxeter number h∨(G₂) = 4).  This is the tunnelling
      probability for the B−L violating process -- the same
      factor that sets M_R = M_Pl exp(−2π²).

      The instanton scale M_R ≈ 3.3 × 10¹⁰ GeV ≫ T_EW ensures
      out-of-equilibrium decay (third Sakharov condition) without
      requiring a separate factor.

  (2) J_lep  =  leptonic Jarlskog invariant

      The unique CP-odd rephasing invariant of the PMNS matrix.
      Derived in Layer 6 from the conjugation invariant of
      SU(3)₃ acting on the democratic nimrep, with NLO correction
      U_e = R₂₃(−φ) · R₁₃(θ_C, δ).

      The CP phase δ = arccos(−λ) traces to the oriented Fano
      plane of the octonions: the directed multiplication table
      of 𝕆 selects a preferred chirality.  Without this
      orientation, J = 0 and no asymmetry forms.

  (3) dim(G₂_fund)  =  7

      The seven directed lines of the Fano plane.  Each line
      is an independent channel through which the oriented
      octonionic multiplication generates the asymmetry.  The
      factor 7 is the dimension of the fundamental representation
      of G₂ = Aut(𝕆), the automorphism group that preserves
      octonionic structure while the Fano orientation breaks CP.

CLOSURE:  Every ingredient -- h∨(G₂), J_lep, dim(7) -- is
derived from E₈ algebraic data in earlier layers.  No external
physics is imported.  The standard leptogenesis machinery
(Casas-Ibarra, Boltzmann equations, washout factors) is the
perturbative dressing of this non-perturbative algebraic result.

References:
    Sakharov, JETP Lett. 5, 24 (1967).
    Planck 2018: η_B = (6.12 ± 0.04) × 10⁻¹⁰.
"""

import math
import sys, os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from .formatting import H, S, box


def derive(alg: dict, pmns: dict):
    """
    Derive the baryon-to-photon ratio from E₈ algebraic data.

    Parameters
    ----------
    alg  : dict from algebra.derive()  -- provides h∨(G₂), dim(7)
    pmns : dict from pmns.derive()     -- provides J_lep

    Returns
    -------
    dict with keys:
        eta_B          : predicted baryon-to-photon ratio
        eta_B_obs      : observed value (Planck 2018)
        ratio          : prediction / observation
        dim_G2_fund    : 7
        J_lep          : leptonic Jarlskog invariant
        S_inst         : instanton action 2π²
    """

    H("LAYER 11:  BARYOGENESIS -- η_B FROM EMERGENCE")

    eta_B_obs = 6.12e-10  # Planck 2018

    # ═══════════════════════════════════════════════════════════════
    #  11.1  The three algebraic factors
    # ═══════════════════════════════════════════════════════════════

    S("11.1  Sakharov conditions as algebraic factors")

    # --- Factor 1: B-L violation (G₂ instanton) ---

    h_dual_G2 = alg['h_dual']['G2']       # = 4
    S_inst = h_dual_G2 * math.pi**2 / 2   # = 2π²
    tunnelling = math.exp(-S_inst)

    print(f"  (1) B−L violation:  G₂ instanton")
    print(f"      h∨(G₂) = {h_dual_G2}")
    print(f"      S = h∨(G₂) π²/2 = {h_dual_G2}×π²/2 = 2π² = {S_inst:.4f}")
    print(f"      exp(−S) = exp(−2π²) = {tunnelling:.6e}")
    print(f"      [Same factor as M_R/M_Pl → out-of-equilibrium guaranteed]")

    # --- Factor 2: CP violation (Fano orientation) ---

    J_lep = pmns['J_lep']
    delta_CP = pmns['delta_CP_deg']

    print(f"")
    print(f"  (2) CP violation:  Fano plane orientation")
    print(f"      J_lep = {J_lep:.6f}")
    print(f"      δ_CP  = {delta_CP:.2f}° = arccos(−λ)")
    print(f"      [Derived in Layer 6 from conjugation invariant]")

    # --- Factor 3: Multiplicity (seven Fano directions) ---

    dim_fund = alg['dim_G2_fund']          # = 7

    print(f"")
    print(f"  (3) Multiplicity:  directed Fano lines")
    print(f"      dim(G₂ fund) = {dim_fund}")
    print(f"      [Seven independent asymmetry channels in 𝕆]")

    # ═══════════════════════════════════════════════════════════════
    #  11.2  The emergence formula
    # ═══════════════════════════════════════════════════════════════

    S("11.2  Baryon-to-photon ratio")

    eta_B = dim_fund * J_lep * tunnelling

    ratio = eta_B / eta_B_obs
    pull_pct = abs(1 - ratio) * 100

    print(f"  η_B = dim(G₂_fund) × J_lep × exp(−h∨(G₂) π²/2)")
    print(f"      = {dim_fund} × {J_lep:.6f} × {tunnelling:.6e}")
    print(f"      = {eta_B:.6e}")
    print(f"")
    print(f"  Observed:   η_B = {eta_B_obs:.2e}  (Planck 2018)")
    print(f"  Predicted:  η_B = {eta_B:.4e}")
    print(f"  Ratio:      {ratio:.4f}")
    print(f"  Agreement:  {pull_pct:.2f}%")

    # ═══════════════════════════════════════════════════════════════
    #  11.3  Physical interpretation
    # ═══════════════════════════════════════════════════════════════

    S("11.3  The matter-antimatter emergence chain")

    n_photons = 1.0 / eta_B

    box([
        f"η_B FROM E₈ ALGEBRAIC DATA  (all couplings derived)",
        f"",
        f"  E₈(1) → G₂(1) × F₄(1)",
        f"    │         │",
        f"    │         └─ F₄: 26 → 8_v ⊕ 8_s ⊕ 8_c ⊕ 1 ⊕ 1",
        f"    │              two singlets → rank-2 seesaw → m₁ = 0",
        f"    │",
        f"    └─ G₂ = Aut(𝕆):",
        f"         h∨(G₂) = {h_dual_G2}  →  instanton tunnelling exp(−2π²)",
        f"         dim(7)  = {dim_fund}   →  seven Fano directions",
        f"         Fano orientation  →  J_lep = {J_lep:.6f}",
        f"",
        f"  η_B = {dim_fund} × {J_lep:.6f} × exp(−2π²)",
        f"      = {eta_B:.4e}",
        f"",
        f"  Planck:  {eta_B_obs:.2e}   ({pull_pct:.2f}% agreement)",
        f"",
        f"  For every {n_photons:.2e} locking events,",
        f"  ~1 extra matter lock survives.",
        f"  We are that remainder.",
    ])

    return {
        'eta_B': eta_B,
        'eta_B_obs': eta_B_obs,
        'ratio': ratio,
        'dim_G2_fund': dim_fund,
        'J_lep': J_lep,
        'S_inst': S_inst,
        'tunnelling': tunnelling,
    }


# ═══════════════════════════════════════════════════════════════════
#  Run standalone
# ═══════════════════════════════════════════════════════════════════

if __name__ == '__main__':
    import io
    old_stdout = sys.stdout
    sys.stdout = io.StringIO()

    import algebra;  alg = algebra.derive()
    import scale;    scl = scale.derive(alg)
    import leptons;  lep = leptons.derive(scl)
    import quarks;   qrk = quarks.derive(alg, scl, lep)
    import wzw;      wzw_data = wzw.derive()
    import ckm;      ckm_data = ckm.derive(wzw_data)
    import pmns;     pmns_data = pmns.derive(wzw_data, lep, ckm_data)

    sys.stdout = old_stdout

    result = derive(alg, pmns_data)
