#!/usr/bin/env python3
"""Regenerate the README scorecard from the live derivation chain.

The scorecard tables in README.md are not hand-written.  They are
generated by this script from the same code path the tests freeze, so
the README cannot drift from the code.  CI runs `--check` on every
push and fails if the two disagree.

    python tools/scorecard.py --write    # update README.md in place
    python tools/scorecard.py --check    # exit 1 if README is stale
"""
import argparse
import contextlib
import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(REPO, "interference"))

BEGIN = "<!-- scorecard:begin (generated by tools/scorecard.py, do not edit by hand) -->"
END = "<!-- scorecard:end -->"


def run_chain():
    import root, masses, mixing, couplings, gravity, dark_sector
    with contextlib.redirect_stdout(io.StringIO()):
        R = root.derive()
        m = masses.derive(R)
        mx = mixing.derive(R, m)
        c = couplings.derive(R, m)
        g = gravity.derive(R, m, mx, c)
        d = dark_sector.derive(R, g)
    return R, m, mx, c, g, d


def generate():
    R, m, mx, c, g, d = run_chain()
    import root
    P = root.PDG_MASSES
    pct = lambda pred, ref: 100.0 * (pred - ref) / ref

    L = []
    A = L.append

    A("### Masses (9/9 within 1%, max error 0.3%)")
    A("")
    A("| Particle | Predicted | PDG | Error | Method |")
    A("|---:|---:|---:|---:|:---|")
    A(f"| e | {m['m_e']:.7f} MeV | {P['e']:.7f} MeV | anchor | CODATA, sole dimensional input |")
    A(f"| μ | {m['m_mu']:.4f} MeV | {P['mu']:.4f} MeV | {pct(m['m_mu'], P['mu']):+.4f}% | Brannen Z₃ (predicted) |")
    A(f"| τ | {m['m_tau']:.3f} MeV | {P['tau']:.3f} MeV | {pct(m['m_tau'], P['tau']):+.4f}% | Brannen Z₃ (predicted) |")
    A(f"| u | {m['m_u']:.3f} MeV | {P['u']:.2f} MeV | {pct(m['m_u'], P['u']):+.1f}% | (38/9) m_e |")
    A(f"| d | {m['m_d']:.3f} MeV | {P['d']:.2f} MeV | {pct(m['m_d'], P['d']):+.1f}% | (83/9) m_e |")
    A(f"| s | {m['m_s']:.1f} MeV | {P['s']:.1f} MeV | {pct(m['m_s'], P['s']):+.1f}% | Rivero + bridge |")
    A(f"| c | {m['m_c']:.1f} MeV | {P['c']:.0f} MeV | {pct(m['m_c'], P['c']):+.2f}% | (217/18) m_μ |")
    A(f"| b | {m['m_b']:.1f} MeV | {P['b']:.0f} MeV | {pct(m['m_b'], P['b']):+.1f}% | Q = Q₀ + h₁₁/K³ |")
    A(f"| t | {m['m_t']/1000:.2f} GeV | {P['t']/1000:.2f} GeV | {pct(m['m_t'], P['t']):+.3f}% | (1165/12) m_τ |")
    A("")
    A("**Mass coordinates.** Unconfined fermions (leptons, top) are at the"
      " propagator pole; confined heavy quarks (c, b) at the self-scale"
      " `m(m)`; light quarks (u, d, s) at the PDG `MS-bar(2 GeV)`"
      " coordinate. The scheme-free content of the light sector is the"
      " RG-invariant ratios, which carry no coordinate at all:"
      f" `m_u/m_d = 38/83` ({(m['mu_over_md']-0.473)/0.017:+.1f}σ vs PDG 0.473(17)),"
      f" `m_s/m_ud = {m['ms_over_mud']:.3f}` ({(m['ms_over_mud']-27.30)/0.08:+.1f}σ"
      " vs 27.30(8), a registered watch),"
      f" `Q_ellipse = {m['Q_ellipse']:.3f}` ({(m['Q_ellipse']-22.1)/0.7:+.1f}σ dispersive,"
      f" {(m['Q_ellipse']-23.4)/0.6:+.1f}σ lattice; the two references disagree)."
      " See `masses.py` for the full treatment.")
    A("")
    A("### Mixing, couplings, gravity, baryogenesis, dark sector")
    A("")
    A("| Sector | Result | Reference | Status |")
    A("|:---|:---|:---|:---|")
    A(f"| Electroweak scale `v_EW` | {m['v_EW_pred_GeV']:.5f} GeV | 246.21965 GeV (from G_F)"
      f" | {1e6*abs(m['v_EW_pred_GeV']/246.219651 - 1.0):.2f} ppm |")
    A(f"| Fine structure `1/α(0)` | {c['inv_alpha_phys']:.9f} | Berkeley Cs 137.035999046(27)"
      f" | pull {(c['inv_alpha_phys']-137.035999046)/27e-9:+.2f}σ (Cs commitment, Rb kill condition registered) |")
    A(f"| Higgs mass `m_H` | {g['mH_pred']:.2f} GeV | 125.20 GeV"
      f" | {pct(g['mH_pred'], 125.20):+.2f}% (2-loop band) |")
    A(f"| CKM ({len(mx['ckm_obs'])} observables) | χ²/n = {mx['chi2_ckm']/len(mx['ckm_obs']):.2f}"
      f" | PDG 2024 | max pull {mx['max_pull_ckm']:.1f}σ |")
    A(f"| PMNS (3 observables) | χ²/n = {mx['chi2_pmns']/3:.2f} | NuFit 6.0"
      f" | predicts δ_CP = {mx['delta_CP_deg']:.1f}° |")
    A(f"| Strong coupling `α_s(M_Z)` | {c['alpha_s_MZ_thresh']:.4f} | PDG 0.1180(9)"
      f" | {pct(c['alpha_s_MZ_thresh'], 0.1180):+.2f}% ({(c['alpha_s_MZ_thresh']-0.1180)/0.0009:+.2f}σ;"
      f" π/32 exact at μ* = {c['mu_star_GeV']:.1f} GeV) |")
    A(f"| Weinberg angle `sin²θ_W` | {g['sin2W']:.6f} | PDG 0.23129(4)"
      f" | pull {(g['sin2W']-0.23129)/4e-5:+.2f}σ |")
    A(f"| W mass `M_W` | {g['M_W_derived']:.3f} GeV | 80.3692(133) world avg"
      f" | pull {(g['M_W_derived']-80.3692)/0.0133:+.2f}σ |")
    A(f"| Z mass `M_Z` | {g['M_Z_derived']:.3f} GeV | 91.188 GeV"
      f" | {pct(g['M_Z_derived'], 91.1876):+.4f}% |")
    A(f"| Newton's constant `G_ind/G_N` | {g['G_ratio_canonical']:.9f} (face-split)"
      f" | 1 | {abs(g['G_ratio_canonical']-1.0):.1e} internal; phase readings"
      f" {g['G_ratio_UV']:.4f} (UV) – {g['G_ratio_broken']:.4f} (broken) |")
    A(f"| Baryon asymmetry `η_B` | {g['eta_B']:.3e} | Planck {g['eta_B_obs']:.2e}"
      f" | {pct(g['eta_B'], g['eta_B_obs']):+.1f}% |")
    A(f"| Dark / baryon ratio `Ω_DM/Ω_b` | `2π − 1` = {d['DM_baryon_ratio']:.4f}"
      f" | Planck {d['DM_baryon_ratio_obs']:.3f}"
      f" | pull {d['pull_DM_baryon']:+.2f}σ |")
    A("")
    A("**Structural predictions:** `m_ν₁ = 0` (rank-2 seesaw, two RH"
      " neutrinos in F₄), normal ordering, and the cosmological-constant"
      " scale `ρ_Λ ~ M_Pl² H₀²` (Volovik–Jacobson–CKN, the 10¹²³ problem"
      " structurally resolved).")
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    readme_path = os.path.join(REPO, "README.md")
    readme = open(readme_path).read()
    if BEGIN not in readme or END not in readme:
        sys.exit("README.md is missing the scorecard markers")
    head, rest = readme.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    updated = head + BEGIN + "\n" + generate() + "\n" + END + tail

    if args.write:
        open(readme_path, "w").write(updated)
        print("README.md scorecard regenerated")
    elif args.check:
        if updated != readme:
            sys.exit("README.md scorecard is stale: run"
                     " `python tools/scorecard.py --write`")
        print("README.md scorecard matches the code")
    else:
        print(generate())


if __name__ == "__main__":
    main()
